var languages = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"label":"Abkhaz","family":"Abkhaz-Adyge"},                              "geometry":{"type":"Point","coordinates":[41.159115,43.056218]}},
{"type":"Feature","properties":{"label":"Abun","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[132.416,-0.57073]}},
{"type":"Feature","properties":{"label":"Achumawi","family":"Palaihnihan"},                              "geometry":{"type":"Point","coordinates":[-121.191,41.0979]}},
{"type":"Feature","properties":{"label":"Aguaruna","family":"Chicham"},                              "geometry":{"type":"Point","coordinates":[-77.9218,-5.30044]}},
{"type":"Feature","properties":{"label":"Hokkaido Ainu","family":"Ainu"},                              "geometry":{"type":"Point","coordinates":[142.46167,43.633654]}},
{"type":"Feature","properties":{"label":"Akabea","family":"Great Andamanese"},                              "geometry":{"type":"Point","coordinates":[92.7818,12.3782]}},
{"type":"Feature","properties":{"label":"Alamblak","family":"Sepik"},                              "geometry":{"type":"Point","coordinates":[143.316,-4.66307]}},
{"type":"Feature","properties":{"label":"Alsea-Yaquina","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-123.94,44.408]}},
{"type":"Feature","properties":{"label":"Amarakaeri","family":"Harakmbut"},                              "geometry":{"type":"Point","coordinates":[-70.5533,-12.4931]}},
{"type":"Feature","properties":{"label":"Arizona Tewa","family":"Kiowa-Tanoan"},                              "geometry":{"type":"Point","coordinates":[-110.381389,35.836667]}},
{"type":"Feature","properties":{"label":"Awa-Cuaiquer","family":"Barbacoan"},                              "geometry":{"type":"Point","coordinates":[-78.3401,1.21652]}},
{"type":"Feature","properties":{"label":"Ayoreo","family":"Zamucoan"},                              "geometry":{"type":"Point","coordinates":[-60.217495,-19.220055]}},
{"type":"Feature","properties":{"label":"Bambara","family":"Mande"},                              "geometry":{"type":"Point","coordinates":[-7.65,12.9]}},
{"type":"Feature","properties":{"label":"Bangime","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-3.77092,14.8116]}},
{"type":"Feature","properties":{"label":"Bardi","family":"Nyulnyulan"},                              "geometry":{"type":"Point","coordinates":[122.906,-16.6274]}},
{"type":"Feature","properties":{"label":"Basque","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-1.31622,43.2787]}},
{"type":"Feature","properties":{"label":"Bella Coola","family":"Salishan"},                              "geometry":{"type":"Point","coordinates":[-126.689,52.3448]}},
{"type":"Feature","properties":{"label":"Bench","family":"Ta-Ne-Omotic"},                              "geometry":{"type":"Point","coordinates":[35.7673,7.04682]}},
{"type":"Feature","properties":{"label":"Berta","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[34.7042,10.6474]}},
{"type":"Feature","properties":{"label":"Bilua","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[156.663,-7.92388]}},
{"type":"Feature","properties":{"label":"Bora","family":"Boran"},                              "geometry":{"type":"Point","coordinates":[-72.257066,-2.000259]}},
{"type":"Feature","properties":{"label":"Bororo","family":"Bororoan"},                              "geometry":{"type":"Point","coordinates":[-55.2004,-16.6029]}},
{"type":"Feature","properties":{"label":"Bukiyip","family":"Nuclear Torricelli"},                              "geometry":{"type":"Point","coordinates":[143.111,-3.47169]}},
{"type":"Feature","properties":{"label":"Bulo Stieng","family":"Austroasiatic"},                              "geometry":{"type":"Point","coordinates":[106.798,11.9777]}},
{"type":"Feature","properties":{"label":"Burushaski","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[74.8236,36.2161]}},
{"type":"Feature","properties":{"label":"Kakua","family":"Kakua-Nukak"},                              "geometry":{"type":"Point","coordinates":[-69.5659,0.88778]}},
{"type":"Feature","properties":{"label":"Caddo","family":"Caddoan"},                              "geometry":{"type":"Point","coordinates":[-93.5,33.33]}},
{"type":"Feature","properties":{"label":"Cahuilla","family":"Uto-Aztecan"},                              "geometry":{"type":"Point","coordinates":[-116.691,33.5324]}},
{"type":"Feature","properties":{"label":"Cayubaba","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-65.4822,-13.2482]}},
{"type":"Feature","properties":{"label":"Central Kanuri","family":"Saharan"},                              "geometry":{"type":"Point","coordinates":[13.13,11.8]}},
{"type":"Feature","properties":{"label":"Central Alaskan Yupik","family":"Eskimo-Aleut"},                              "geometry":{"type":"Point","coordinates":[-161.486,60.3062]}},
{"type":"Feature","properties":{"label":"Shawi","family":"Cahuapanan"},                              "geometry":{"type":"Point","coordinates":[-76.8252,-5.63764]}},
{"type":"Feature","properties":{"label":"Chimariko","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-123,41]}},
{"type":"Feature","properties":{"label":"Clatsop-Shoalwater Chinook","family":"Chinookan"},                              "geometry":{"type":"Point","coordinates":[-119.166,45.1729]}},
{"type":"Feature","properties":{"label":"Chipaya","family":"Uru-Chipaya"},                              "geometry":{"type":"Point","coordinates":[-67.89633,-18.73951]}},
{"type":"Feature","properties":{"label":"Lomeriano-Ignaciano Chiquitano","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-61.817795,-16.769554]}},
{"type":"Feature","properties":{"label":"Cholón","family":"Hibito-Cholon"},                              "geometry":{"type":"Point","coordinates":[-75.9621,-9.23129]}},
{"type":"Feature","properties":{"label":"Chukchi","family":"Chukotko-Kamchatkan"},                              "geometry":{"type":"Point","coordinates":[170.045,68.6436]}},
{"type":"Feature","properties":{"label":"Coahuilteco","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-97.89,28.2589]}},
{"type":"Feature","properties":{"label":"Hanis","family":"Coosan"},                              "geometry":{"type":"Point","coordinates":[-124.16,43.4413]}},
{"type":"Feature","properties":{"label":"Creek","family":"Muskogean"},                              "geometry":{"type":"Point","coordinates":[-87.5,31]}},
{"type":"Feature","properties":{"label":"Cuitlatec","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-100.5,18.1]}},
{"type":"Feature","properties":{"label":"Daga","family":"Dagan"},                              "geometry":{"type":"Point","coordinates":[149.263,-9.9747]}},
{"type":"Feature","properties":{"label":"Jaminjung-Ngaliwurru","family":"Mirndi"},                              "geometry":{"type":"Point","coordinates":[130.06,-15.0558]}},
{"type":"Feature","properties":{"label":"Duna","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[142.475,-5.41439]}},
{"type":"Feature","properties":{"label":"Emberá-Catío","family":"Chocoan"},                              "geometry":{"type":"Point","coordinates":[-76.7476,7.52721]}},
{"type":"Feature","properties":{"label":"Teko","family":"Tupian"},                              "geometry":{"type":"Point","coordinates":[-52.3699,3.23694]}},
{"type":"Feature","properties":{"label":"Ese Ejja","family":"Pano-Tacanan"},                              "geometry":{"type":"Point","coordinates":[-67.515,-11.7268]}},
{"type":"Feature","properties":{"label":"Even","family":"Tungusic"},                              "geometry":{"type":"Point","coordinates":[130.914,70.6687]}},
{"type":"Feature","properties":{"label":"Fulniô","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-37.1402,-9.02591]}},
{"type":"Feature","properties":{"label":"Fur","family":"Furan"},                              "geometry":{"type":"Point","coordinates":[23.6401,12.0455]}},
{"type":"Feature","properties":{"label":"Gaam","family":"Eastern Jebel"},                              "geometry":{"type":"Point","coordinates":[33.9797,11.4674]}},
{"type":"Feature","properties":{"label":"Gaagudju","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[132.643,-12.5176]}},
{"type":"Feature","properties":{"label":"Garrwa","family":"Garrwan"},                              "geometry":{"type":"Point","coordinates":[137.72014,-17.4504]}},
{"type":"Feature","properties":{"label":"Amur Nivkh","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[140.681,52.59]}},
{"type":"Feature","properties":{"label":"Gooniyandi","family":"Bunaban"},                              "geometry":{"type":"Point","coordinates":[126.351,-18.4073]}},
{"type":"Feature","properties":{"label":"Grass Koiari","family":"Koiarian"},                              "geometry":{"type":"Point","coordinates":[147.437,-9.51218]}},
{"type":"Feature","properties":{"label":"Guahibo","family":"Guahiboan"},                              "geometry":{"type":"Point","coordinates":[-68.9839,5.81736]}},
{"type":"Feature","properties":{"label":"Guató","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-57.2897,-17.8696]}},
{"type":"Feature","properties":{"label":"Hadza","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[35.0458,-3.83115]}},
{"type":"Feature","properties":{"label":"Halh Mongolian","family":"Mongolic-Khitan"},                              "geometry":{"type":"Point","coordinates":[106.289,48.324]}},
{"type":"Feature","properties":{"label":"Hattic","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[40.3333,33.9833]}},
{"type":"Feature","properties":{"label":"Highland Oaxaca Chontal","family":"Tequistlatecan"},                              "geometry":{"type":"Point","coordinates":[-95.7301,16.1849]}},
{"type":"Feature","properties":{"label":"Hixkaryána","family":"Cariban"},                              "geometry":{"type":"Point","coordinates":[-58.80153,-0.16265]}},
{"type":"Feature","properties":{"label":"Huehuetla Tepehua","family":"Totonacan"},                              "geometry":{"type":"Point","coordinates":[-97.9347,20.6189]}},
{"type":"Feature","properties":{"label":"Hup","family":"Nadahup"},                              "geometry":{"type":"Point","coordinates":[-69.8359,0.58622]}},
{"type":"Feature","properties":{"label":"Imonda","family":"Border"},                              "geometry":{"type":"Point","coordinates":[141.171,-3.31228]}},
{"type":"Feature","properties":{"label":"Ineseño","family":"Chumashan"},                              "geometry":{"type":"Point","coordinates":[-120.08,34.6169]}},
{"type":"Feature","properties":{"label":"Ingush","family":"Nakh-Daghestanian"},                              "geometry":{"type":"Point","coordinates":[45.03,43.11]}},
{"type":"Feature","properties":{"label":"Irántxe-Münkü","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-57.9806,-12.7178]}},
{"type":"Feature","properties":{"label":"Irish","family":"Indo-European"},                              "geometry":{"type":"Point","coordinates":[-7.61509,53.2186]}},
{"type":"Feature","properties":{"label":"Itonama","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-64.35748,-12.80431]}},
{"type":"Feature","properties":{"label":"Iu Mien","family":"Hmong-Mien"},                              "geometry":{"type":"Point","coordinates":[101.17,20.83]}},
{"type":"Feature","properties":{"label":"Madi","family":"Arawan"},                              "geometry":{"type":"Point","coordinates":[-66.5662,-7.62223]}},
{"type":"Feature","properties":{"label":"South-Eastern Ju","family":"Kxa"},                              "geometry":{"type":"Point","coordinates":[20.7673,-19.688]}},
{"type":"Feature","properties":{"label":"Kaingang","family":"Nuclear-Macro-Je"},                              "geometry":{"type":"Point","coordinates":[-52.5394,-27.7671]}},
{"type":"Feature","properties":{"label":"Central Kalapuya","family":"Kalapuyan"},                              "geometry":{"type":"Point","coordinates":[-123.925,44.9861]}},
{"type":"Feature","properties":{"label":"Kambaata","family":"Afro-Asiatic"},                              "geometry":{"type":"Point","coordinates":[37.9088,7.37582]}},
{"type":"Feature","properties":{"label":"Kamu","family":"Eastern Daly"},                              "geometry":{"type":"Point","coordinates":[131.098,-13.5393]}},
{"type":"Feature","properties":{"label":"Katukína-Kanamarí","family":"Katukinan"},                              "geometry":{"type":"Point","coordinates":[-68.7678,-6.45399]}},
{"type":"Feature","properties":{"label":"Kanoê","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-64.5812,-12.1789]}},
{"type":"Feature","properties":{"label":"Kariri","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-40.487275,-7.434628]}},
{"type":"Feature","properties":{"label":"Karok","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-123.315,41.8228]}},
{"type":"Feature","properties":{"label":"Kayardild","family":"Tangkic"},                              "geometry":{"type":"Point","coordinates":[139.489,-17.0695]}},
{"type":"Feature","properties":{"label":"Kenuzi-Dongola","family":"Nubian"},                              "geometry":{"type":"Point","coordinates":[31.8992,21.2837]}},
{"type":"Feature","properties":{"label":"Ket","family":"Yeniseian"},                              "geometry":{"type":"Point","coordinates":[87.5466,63.7551]}},
{"type":"Feature","properties":{"label":"K'iche","family":"Mayan"},                              "geometry":{"type":"Point","coordinates":[-91.1696,14.5278]}},
{"type":"Feature","properties":{"label":"Kitja","family":"Jarrakan"},                              "geometry":{"type":"Point","coordinates":[127.392,-17.5758]}},
{"type":"Feature","properties":{"label":"Klamath-Modoc","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-121.704,42.5861]}},
{"type":"Feature","properties":{"label":"Koyraboro Senni Songhai","family":"Songhay"},                              "geometry":{"type":"Point","coordinates":[-0.55187,16.9634]}},
{"type":"Feature","properties":{"label":"Krongo","family":"Kadugli-Krongo"},                              "geometry":{"type":"Point","coordinates":[30.003,10.514]}},
{"type":"Feature","properties":{"label":"Kunama","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[37.5292,14.5879]}},
{"type":"Feature","properties":{"label":"Kuot","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[151.537,-3.06952]}},
{"type":"Feature","properties":{"label":"Kusunda","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[82.6,28.33]}},
{"type":"Feature","properties":{"label":"Kutenai","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-115.065,48.7892]}},
{"type":"Feature","properties":{"label":"Kwaza","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-61.1833,-11.6667]}},
{"type":"Feature","properties":{"label":"Kyongsangdo","family":"Koreanic"},                              "geometry":{"type":"Point","coordinates":[128.3,35.3]}},
{"type":"Feature","properties":{"label":"Laal","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[17.6143,10.0063]}},
{"type":"Feature","properties":{"label":"Lakota","family":"Siouan"},                              "geometry":{"type":"Point","coordinates":[-103.95,46.3699]}},
{"type":"Feature","properties":{"label":"Lakondê","family":"Nambiquaran"},                              "geometry":{"type":"Point","coordinates":[-60.5,-13.2]}},
{"type":"Feature","properties":{"label":"Lango (Uganda)","family":"Nilotic"},                              "geometry":{"type":"Point","coordinates":[33.0553,2.13867]}},
{"type":"Feature","properties":{"label":"Lao","family":"Tai-Kadai"},                              "geometry":{"type":"Point","coordinates":[102.46,19]}},
{"type":"Feature","properties":{"label":"Lavukaleve","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[159.119,-9.05569]}},
{"type":"Feature","properties":{"label":"Leco","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-67.8818,-15.0092]}},
{"type":"Feature","properties":{"label":"Maba (Chad)","family":"Maban"},                              "geometry":{"type":"Point","coordinates":[20.8889,12.89147]}},
{"type":"Feature","properties":{"label":"Ma'di","family":"Central Sudanic"},                              "geometry":{"type":"Point","coordinates":[31.8471,3.62499]}},
{"type":"Feature","properties":{"label":"Maybrat-Karon","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[132.591,-1.3679]}},
{"type":"Feature","properties":{"label":"Malinaltepec Me'phaa","family":"Otomanguean"},                              "geometry":{"type":"Point","coordinates":[-98.6322,17.2122]}},
{"type":"Feature","properties":{"label":"Mangarrayi","family":"Mangarrayi-Maran"},                              "geometry":{"type":"Point","coordinates":[133.5,-14.8]}},
{"type":"Feature","properties":{"label":"Mapudungun","family":"Araucanian"},                              "geometry":{"type":"Point","coordinates":[-71.277,-38.7392]}},
{"type":"Feature","properties":{"label":"Marithiel","family":"Western Daly"},                              "geometry":{"type":"Point","coordinates":[130.237,-13.8818]}},
{"type":"Feature","properties":{"label":"Maricopa","family":"Cochimi-Yuman"},                              "geometry":{"type":"Point","coordinates":[-111.749,33.5123]}},
{"type":"Feature","properties":{"label":"Mawng","family":"Iwaidjan Proper"},                              "geometry":{"type":"Point","coordinates":[133.376,-11.66]}},
{"type":"Feature","properties":{"label":"Menya","family":"Angan"},                              "geometry":{"type":"Point","coordinates":[146.071,-7.17425]}},
{"type":"Feature","properties":{"label":"Mískito","family":"Misumalpan"},                              "geometry":{"type":"Point","coordinates":[-84.2942,15.1576]}},
{"type":"Feature","properties":{"label":"Mohawk","family":"Iroquoian"},                              "geometry":{"type":"Point","coordinates":[-74.66836,43.72]}},
{"type":"Feature","properties":{"label":"Molale","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-122.857,44.556]}},
{"type":"Feature","properties":{"label":"Mosetén-Chimané","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-67.83756,-14.64448]}},
{"type":"Feature","properties":{"label":"Movima","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-65.6348,-13.8115]}},
{"type":"Feature","properties":{"label":"Mullukmulluk","family":"Northern Daly"},                              "geometry":{"type":"Point","coordinates":[130.664,-13.427]}},
{"type":"Feature","properties":{"label":"Muniche","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-76.426712,-5.7441796]}},
{"type":"Feature","properties":{"label":"Murle","family":"Surmic"},                              "geometry":{"type":"Point","coordinates":[33.988,6.69756]}},
{"type":"Feature","properties":{"label":"Murriny Patha","family":"Southern Daly"},                              "geometry":{"type":"Point","coordinates":[129.70152,-14.74852]}},
{"type":"Feature","properties":{"label":"Murui Huitoto","family":"Huitotoan"},                              "geometry":{"type":"Point","coordinates":[-73.8331,-1.13669]}},
{"type":"Feature","properties":{"label":"Nakara","family":"Maningrida"},                              "geometry":{"type":"Point","coordinates":[134.32729,-12.07653]}},
{"type":"Feature","properties":{"label":"Nama (Namibia)","family":"Khoe-Kwadi"},                              "geometry":{"type":"Point","coordinates":[17.9767,-25.0747]}},
{"type":"Feature","properties":{"label":"Nanti","family":"Arawakan"},                              "geometry":{"type":"Point","coordinates":[-72.3507,-12.1018]}},
{"type":"Feature","properties":{"label":"Nara","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[37.499,15.3251]}},
{"type":"Feature","properties":{"label":"Natchez","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-91.33,31.75]}},
{"type":"Feature","properties":{"label":"Tundra Nenets","family":"Uralic"},                              "geometry":{"type":"Point","coordinates":[71.0234,66.1775]}},
{"type":"Feature","properties":{"label":"Ngarinyin","family":"Worrorran"},                              "geometry":{"type":"Point","coordinates":[126.433,-16.4006]}},
{"type":"Feature","properties":{"label":"Nihali","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[76.3318,21.1886]}},
{"type":"Feature","properties":{"label":"Nisga'a","family":"Tsimshian"},                              "geometry":{"type":"Point","coordinates":[-129.192,55.199]}},
{"type":"Feature","properties":{"label":"North Slavey","family":"Athabaskan-Eyak-Tlingit"},                              "geometry":{"type":"Point","coordinates":[-123.641,63.2671]}},
{"type":"Feature","properties":{"label":"Northwest Maidu","family":"Maiduan"},                              "geometry":{"type":"Point","coordinates":[-121.368,39.6721]}},
{"type":"Feature","properties":{"label":"Georgian","family":"Kartvelian"},                              "geometry":{"type":"Point","coordinates":[43.78613,41.850397]}},
{"type":"Feature","properties":{"label":"Limilngan","family":"Limilngan-Wulna"},                              "geometry":{"type":"Point","coordinates":[131.845,-12.4294]}},
{"type":"Feature","properties":{"label":"Marind","family":"Anim"},                              "geometry":{"type":"Point","coordinates":[140.009,-8.15651]}},
{"type":"Feature","properties":{"label":"Sentani","family":"Sentanic"},                              "geometry":{"type":"Point","coordinates":[140.512,-2.6013]}},
{"type":"Feature","properties":{"label":"Nimboran","family":"Nimboranic"},                              "geometry":{"type":"Point","coordinates":[140.179,-2.5803]}},
{"type":"Feature","properties":{"label":"Wubuy","family":"Gunwinyguan"},                              "geometry":{"type":"Point","coordinates":[135.753,-14.2623]}},
{"type":"Feature","properties":{"label":"Nuu-chah-nulth","family":"Wakashan"},                              "geometry":{"type":"Point","coordinates":[-126.67,49.67]}},
{"type":"Feature","properties":{"label":"Páez","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-76.31254,2.61516]}},
{"type":"Feature","properties":{"label":"Pilagá","family":"Guaicuruan"},                              "geometry":{"type":"Point","coordinates":[-60.1537,-25.0058]}},
{"type":"Feature","properties":{"label":"Pirahã","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-61.8167,-6.77713]}},
{"type":"Feature","properties":{"label":"Puinave","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-67.6886,3.92974]}},
{"type":"Feature","properties":{"label":"Purepecha","family":"Tarascan"},                              "geometry":{"type":"Point","coordinates":[-101.631,19.2467]}},
{"type":"Feature","properties":{"label":"Qawasqar","family":"Kawesqar"},                              "geometry":{"type":"Point","coordinates":[-74.707536,-49.303195]}},
{"type":"Feature","properties":{"label":"Quileute","family":"Chimakuan"},                              "geometry":{"type":"Point","coordinates":[-124.603,47.9106]}},
{"type":"Feature","properties":{"label":"Rama","family":"Chibchan"},                              "geometry":{"type":"Point","coordinates":[-83.8571,11.5007]}},
{"type":"Feature","properties":{"label":"Rotokas","family":"North Bougainville"},                              "geometry":{"type":"Point","coordinates":[155.154,-5.94339]}},
{"type":"Feature","properties":{"label":"Salinan","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-121.718,37.6646]}},
{"type":"Feature","properties":{"label":"Sáliba","family":"Jodi-Saliban"},                              "geometry":{"type":"Point","coordinates":[-69.3843,5.30115]}},
{"type":"Feature","properties":{"label":"Sanapaná","family":"Lengua-Mascoy"},                              "geometry":{"type":"Point","coordinates":[-58.38,-22.49]}},
{"type":"Feature","properties":{"label":"Sandawe","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[35.4808,-5.26918]}},
{"type":"Feature","properties":{"label":"San Dionisio del Mar Huave","family":"Huavean"},                              "geometry":{"type":"Point","coordinates":[-94.7001,16.3514]}},
{"type":"Feature","properties":{"label":"Santiago del Estero Quichua","family":"Quechuan"},                              "geometry":{"type":"Point","coordinates":[-63.2466,-27.821]}},
{"type":"Feature","properties":{"label":"Savosavo","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[159.814,-9.12853]}},
{"type":"Feature","properties":{"label":"Seri","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-112.384,28.9877]}},
{"type":"Feature","properties":{"label":"Shabo","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[35.223,7.64407]}},
{"type":"Feature","properties":{"label":"Shasta","family":"Shastan"},                              "geometry":{"type":"Point","coordinates":[-122.738,41.7587]}},
{"type":"Feature","properties":{"label":"Sheko","family":"Dizoid"},                              "geometry":{"type":"Point","coordinates":[35.2826,7.05022]}},
{"type":"Feature","properties":{"label":"Siamou","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-4.92143,10.998]}},
{"type":"Feature","properties":{"label":"Siona-Tetete","family":"Tucanoan"},                              "geometry":{"type":"Point","coordinates":[-76.0237,0.31733]}},
{"type":"Feature","properties":{"label":"Siuslaw","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-124.379,42.5111]}},
{"type":"Feature","properties":{"label":"Southern Yukaghir","family":"Yukaghir"},                              "geometry":{"type":"Point","coordinates":[154.375,64.218]}},
{"type":"Feature","properties":{"label":"Southern Haida","family":"Haida"},                              "geometry":{"type":"Point","coordinates":[-132.008,53.2616]}},
{"type":"Feature","properties":{"label":"Southeastern Pomo","family":"Pomoan"},                              "geometry":{"type":"Point","coordinates":[-122.599,38.9354]}},
{"type":"Feature","properties":{"label":"Southern Sierra Miwok","family":"Miwok-Costanoan"},                              "geometry":{"type":"Point","coordinates":[-120.507,38.2363]}},
{"type":"Feature","properties":{"label":"Southern Aymara","family":"Aymaran"},                              "geometry":{"type":"Point","coordinates":[-70.3442,-17.1417]}},
{"type":"Feature","properties":{"label":"Sulka","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[151.891,-5.03471]}},
{"type":"Feature","properties":{"label":"Sumerian","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[45.6667,31.3]}},
{"type":"Feature","properties":{"label":"Swampy Cree","family":"Algic"},                              "geometry":{"type":"Point","coordinates":[-95,56]}},
{"type":"Feature","properties":{"label":"Tabo","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[143.305,-8.09387]}},
{"type":"Feature","properties":{"label":"Taiap","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[144.506,-4.05047]}},
{"type":"Feature","properties":{"label":"Takelma","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-123.452,42.423]}},
{"type":"Feature","properties":{"label":"Tehuelche","family":"Chonan"},                              "geometry":{"type":"Point","coordinates":[-68.3235,-47.5796]}},
{"type":"Feature","properties":{"label":"Thayore","family":"Pama-Nyungan"},                              "geometry":{"type":"Point","coordinates":[142.034,-14.8159]}},
{"type":"Feature","properties":{"label":"Ticuna","family":"Ticuna-Yuri"},                              "geometry":{"type":"Point","coordinates":[-69.8723,-3.66289]}},
{"type":"Feature","properties":{"label":"Tidore","family":"North Halmahera"},                              "geometry":{"type":"Point","coordinates":[127.746,0.02461]}},
{"type":"Feature","properties":{"label":"Timucua","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-82.3132,30.3027]}},
{"type":"Feature","properties":{"label":"Tiwi","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[130.949,-11.6308]}},
{"type":"Feature","properties":{"label":"Tol","family":"Jicaquean"},                              "geometry":{"type":"Point","coordinates":[-87.0372,14.6686]}},
{"type":"Feature","properties":{"label":"Tommo So Dogon","family":"Dogon"},                              "geometry":{"type":"Point","coordinates":[-3.28,14.756]}},
{"type":"Feature","properties":{"label":"Tonkawa","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-96.75,30.25]}},
{"type":"Feature","properties":{"label":"Totontepec Mixe","family":"Mixe-Zoque"},                              "geometry":{"type":"Point","coordinates":[-96.0179,17.2157]}},
{"type":"Feature","properties":{"label":"Trumai","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-53.5717,-11.8119]}},
{"type":"Feature","properties":{"label":"Tukang Besi North","family":"Austronesian"},                              "geometry":{"type":"Point","coordinates":[123.578,-5.30994]}},
{"type":"Feature","properties":{"label":"Tunica","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-92.5403,30.9888]}},
{"type":"Feature","properties":{"label":"Tuvinian","family":"Turkic"},                              "geometry":{"type":"Point","coordinates":[94.36667,51.7]}},
{"type":"Feature","properties":{"label":"Urarina","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-75.4211,-4.44006]}},
{"type":"Feature","properties":{"label":"Urningangg","family":"Giimbiyu"},                              "geometry":{"type":"Point","coordinates":[133.023,-13.4766]}},
{"type":"Feature","properties":{"label":"Wageman","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[131.893,-13.8627]}},
{"type":"Feature","properties":{"label":"Wappo","family":"Yuki-Wappo"},                              "geometry":{"type":"Point","coordinates":[-122.5,38.25]}},
{"type":"Feature","properties":{"label":"Bauni","family":"Sko"},                              "geometry":{"type":"Point","coordinates":[142.012,-3.07263]}},
{"type":"Feature","properties":{"label":"Warao","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-59.3528,7.50851]}},
{"type":"Feature","properties":{"label":"Wardaman","family":"Yangmanic"},                              "geometry":{"type":"Point","coordinates":[132.604,-15.4155]}},
{"type":"Feature","properties":{"label":"Wari'","family":"Chapacuran"},                              "geometry":{"type":"Point","coordinates":[-64.56152,-10.69948]}},
{"type":"Feature","properties":{"label":"Washo","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-119.64,38.8184]}},
{"type":"Feature","properties":{"label":"Western Keres","family":"Keresan"},                              "geometry":{"type":"Point","coordinates":[-107.517,34.9733]}},
{"type":"Feature","properties":{"label":"Wichí Lhamtés Nocten","family":"Matacoan"},                              "geometry":{"type":"Point","coordinates":[-63.5971,-21.988]}},
{"type":"Feature","properties":{"label":"Wintu","family":"Wintuan"},                              "geometry":{"type":"Point","coordinates":[-122.445,39.7176]}},
{"type":"Feature","properties":{"label":"Xinca-Chiquimulilla","family":"Xincan"},                              "geometry":{"type":"Point","coordinates":[-90.380259,14.083301]}},
{"type":"Feature","properties":{"label":"Yagua","family":"Peba-Yagua"},                              "geometry":{"type":"Point","coordinates":[-72.2186,-3.42913]}},
{"type":"Feature","properties":{"label":"Northwest Sahaptin","family":"Sahaptian"},                              "geometry":{"type":"Point","coordinates":[-120.756,46.2655]}},
{"type":"Feature","properties":{"label":"Yana","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-121.608,39.2769]}},
{"type":"Feature","properties":{"label":"Yanomám","family":"Yanomamic"},                              "geometry":{"type":"Point","coordinates":[-62.8522,2.48999]}},
{"type":"Feature","properties":{"label":"Yau (Morobe Province)","family":"Nuclear Trans New Guinea"},                              "geometry":{"type":"Point","coordinates":[146.841,-6.08274]}},
{"type":"Feature","properties":{"label":"Yimas","family":"Lower Sepik-Ramu"},                              "geometry":{"type":"Point","coordinates":[143.572,-4.71731]}},
{"type":"Feature","properties":{"label":"Northern Yokuts","family":"Yokutsan"},                              "geometry":{"type":"Point","coordinates":[-119.721,36.3167]}},
{"type":"Feature","properties":{"label":"Yoruba","family":"Atlantic-Congo"},                              "geometry":{"type":"Point","coordinates":[3.67225,7.15345]}},
{"type":"Feature","properties":{"label":"Yuchi","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-86.75,35.75]}},
{"type":"Feature","properties":{"label":"Yuracaré","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-65.1224,-16.7479]}},
{"type":"Feature","properties":{"label":"Záparo","family":"Zaparoan"},                              "geometry":{"type":"Point","coordinates":[-76.364,-1.99871]}},
{"type":"Feature","properties":{"label":"Zuni","family":"Isolate"},                              "geometry":{"type":"Point","coordinates":[-108.782,35.0056]}}]};