var languages = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"label":"Daga","family":"Dagan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[149.263,-9.9747]}},
{"type":"Feature","properties":{"label":"Yurok","family":"Algic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-123.824,41.3262]}},
{"type":"Feature","properties":{"label":"Koyraboro Senni Songhai","family":"Songhay","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-0.55187,16.9634]}},
{"type":"Feature","properties":{"label":"Savosavo","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[159.814,-9.12853]}},
{"type":"Feature","properties":{"label":"Rama","family":"Katukinan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-83.8571,11.5007]}},
{"type":"Feature","properties":{"label":"Mawng","family":"Iwaidjan Proper","insample":"1"},                              "geometry":{"type":"Point","coordinates":[133.376,-11.66]}},
{"type":"Feature","properties":{"label":"Hattic","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[40.3333,33.9833]}},
{"type":"Feature","properties":{"label":"Nivkh","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[140.681,52.59]}},
{"type":"Feature","properties":{"label":"Purepecha","family":"Tarascan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-101.631,19.2467]}},
{"type":"Feature","properties":{"label":"Nimboran","family":"Nimboranic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[140.179,-2.5803]}},
{"type":"Feature","properties":{"label":"Burushaski","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[74.8236,36.2161]}},
{"type":"Feature","properties":{"label":"Hupdë","family":"Naduhup","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-69.8359,0.58622]}},
{"type":"Feature","properties":{"label":"Kwaza","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-61.1833,-11.6667]}},
{"type":"Feature","properties":{"label":"Bilua","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[156.663,-7.92388]}},
{"type":"Feature","properties":{"label":"Irántxe-Münkü","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-57.9806,-12.7178]}},
{"type":"Feature","properties":{"label":"San Dionisio del Mar Huave","family":"Tai-Kadai","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-94.7001,16.3514]}},
{"type":"Feature","properties":{"label":"Korean","family":"Koreanic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[128,37.5]}},
{"type":"Feature","properties":{"label":"Shawi","family":"Cahuapanan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-76.8252,-5.63764]}},
{"type":"Feature","properties":{"label":"Thayore","family":"Pama-Nyungan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[142.034,-14.8159]}},
{"type":"Feature","properties":{"label":"Wardaman","family":"Yangmanic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[132.604,-15.4155]}},
{"type":"Feature","properties":{"label":"Central Kanuri","family":"Saharan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[13.13,11.8]}},
{"type":"Feature","properties":{"label":"Tukang Besi North","family":"Austronesian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[123.578,-5.30994]}},
{"type":"Feature","properties":{"label":"Northwest Sahaptin","family":"Iberian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-120.756,46.2655]}},
{"type":"Feature","properties":{"label":"Bora","family":"Boran","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-68.9093,-2.91467]}},
{"type":"Feature","properties":{"label":"Yagua","family":"Peba-Yagua","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-72.2186,-3.42913]}},
{"type":"Feature","properties":{"label":"Hokkaido Ainu","family":"Ainu","insample":"1"},                              "geometry":{"type":"Point","coordinates":[142.46167,43.633654]}},
{"type":"Feature","properties":{"label":"Lango (Uganda)","family":"Nilotic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[33.0553,2.13867]}},
{"type":"Feature","properties":{"label":"Kamu","family":"Eastern Daly","insample":"1"},                              "geometry":{"type":"Point","coordinates":[131.098,-13.5393]}},
{"type":"Feature","properties":{"label":"Alsea-Yaquina","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-123.94,44.408]}},
{"type":"Feature","properties":{"label":"Nihali","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[76.3318,21.1886]}},
{"type":"Feature","properties":{"label":"Ket","family":"Yeniseian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[87.5466,63.7551]}},
{"type":"Feature","properties":{"label":"Kusunda","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[82.6,28.33]}},
{"type":"Feature","properties":{"label":"Marithiel","family":"Western Daly","insample":"1"},                              "geometry":{"type":"Point","coordinates":[130.237,-13.8818]}},
{"type":"Feature","properties":{"label":"Grass Koiari","family":"Koiarian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[147.437,-9.51218]}},
{"type":"Feature","properties":{"label":"Irish","family":"Indo-European","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-7.61509,53.2186]}},
{"type":"Feature","properties":{"label":"Katukína-Kanamarí","family":"Ainu","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-68.7678,-6.45399]}},
{"type":"Feature","properties":{"label":"Kiowa","family":"Kiowa-Tanoan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-98.9042,34.9403]}},
{"type":"Feature","properties":{"label":"Halh Mongolian","family":"Mongolic-Khitan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[106.289,48.324]}},
{"type":"Feature","properties":{"label":"Mosetén-Chimané","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-67.83756,-14.64448]}},
{"type":"Feature","properties":{"label":"Navajo","family":"Athabaskan-Eyak-Tlingit","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-110.082,36.2106]}},
{"type":"Feature","properties":{"label":"Sandawe","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[35.4808,-5.26918]}},
{"type":"Feature","properties":{"label":"Xavánte","family":"Nuclear-Macro-Je","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-52.4367,-14.3017]}},
{"type":"Feature","properties":{"label":"Yecuatla Totonac","family":"Totonacan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-96.8741,20.1765]}},
{"type":"Feature","properties":{"label":"Sáliba","family":"Jodi-Saliban","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-69.3843,5.30115]}},
{"type":"Feature","properties":{"label":"Mullukmulluk","family":"Northern Daly","insample":"1"},                              "geometry":{"type":"Point","coordinates":[130.664,-13.427]}},
{"type":"Feature","properties":{"label":"Nakara","family":"Maningrida","insample":"1"},                              "geometry":{"type":"Point","coordinates":[134.32729,-12.07653]}},
{"type":"Feature","properties":{"label":"Coahuilteco","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-97.89,28.2589]}},
{"type":"Feature","properties":{"label":"Seri","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-112.384,28.9877]}},
{"type":"Feature","properties":{"label":"Mangarrayi","family":"Mangarrayi-Maran","insample":"1"},                              "geometry":{"type":"Point","coordinates":[138.5,-14.8]}},
{"type":"Feature","properties":{"label":"Maba (Chad)","family":"Maban","insample":"1"},                              "geometry":{"type":"Point","coordinates":[20.8889,12.89147]}},
{"type":"Feature","properties":{"label":"Kalaallisut","family":"Mpur","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-52.864,69.3761]}},
{"type":"Feature","properties":{"label":"Menya","family":"Angan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[146.071,-7.17425]}},
{"type":"Feature","properties":{"label":"Limilngan","family":"Limilngan-Wulna","insample":"1"},                              "geometry":{"type":"Point","coordinates":[131.845,-12.4294]}},
{"type":"Feature","properties":{"label":"Tiwi","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[130.949,-11.6308]}},
{"type":"Feature","properties":{"label":"Yau (Morobe Province)","family":"Nuclear Trans New Guinea","insample":"1"},                              "geometry":{"type":"Point","coordinates":[146.841,-6.08274]}},
{"type":"Feature","properties":{"label":"Krongo","family":"Kadugli-Krongo","insample":"1"},                              "geometry":{"type":"Point","coordinates":[30.003,10.514]}},
{"type":"Feature","properties":{"label":"Duna","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[142.475,-5.41439]}},
{"type":"Feature","properties":{"label":"Ingush","family":"Nakh-Daghestanian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[45.03,43.11]}},
{"type":"Feature","properties":{"label":"Sanapaná","family":"Lengua-Mascoy","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-58,-23.2]}},
{"type":"Feature","properties":{"label":"Bulo Stieng","family":"Austroasiatic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[106.798,11.9777]}},
{"type":"Feature","properties":{"label":"Kuot","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[151.537,-3.06952]}},
{"type":"Feature","properties":{"label":"Marind","family":"Anim","insample":"1"},                              "geometry":{"type":"Point","coordinates":[140.009,-8.15651]}},
{"type":"Feature","properties":{"label":"Záparo","family":"Puelche","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-76.364,-1.99871]}},
{"type":"Feature","properties":{"label":"Jaminjung-Ngaliwurru","family":"Mirndi","insample":"1"},                              "geometry":{"type":"Point","coordinates":[130.06,-15.0558]}},
{"type":"Feature","properties":{"label":"Tonkawa","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-96.75,30.25]}},
{"type":"Feature","properties":{"label":"Laal","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[17.6143,10.0063]}},
{"type":"Feature","properties":{"label":"Natchez","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-91.33,31.75]}},
{"type":"Feature","properties":{"label":"Lake Miwok","family":"Miwok-Costanoan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-122.621,39.0021]}},
{"type":"Feature","properties":{"label":"Wintu","family":"Wintuan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-122.445,39.7176]}},
{"type":"Feature","properties":{"label":"Manipuri","family":"Sino-Tibetan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[93.3426,24.4409]}},
{"type":"Feature","properties":{"label":"Clatsop-Shoalwater Chinook","family":"Chinookan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-119.166,45.1729]}},
{"type":"Feature","properties":{"label":"Achumawi","family":"Palaihnihan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-121.191,41.0979]}},
{"type":"Feature","properties":{"label":"Gooniyandi","family":"Bunaban","insample":"1"},                              "geometry":{"type":"Point","coordinates":[126.351,-18.4073]}},
{"type":"Feature","properties":{"label":"Popti'","family":"Ramanos","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-91.6633,15.6609]}},
{"type":"Feature","properties":{"label":"Nara","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[37.499,15.3251]}},
{"type":"Feature","properties":{"label":"Pilagá","family":"Mayan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-60.1537,-25.0058]}},
{"type":"Feature","properties":{"label":"Bauni","family":"Sko","insample":"1"},                              "geometry":{"type":"Point","coordinates":[142.012,-3.07263]}},
{"type":"Feature","properties":{"label":"Maybrat-Karon","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[132.591,-1.3679]}},
{"type":"Feature","properties":{"label":"Sentani","family":"Sentanic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[140.512,-2.6013]}},
{"type":"Feature","properties":{"label":"Guató","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-57.2897,-17.8696]}},
{"type":"Feature","properties":{"label":"Yaqui","family":"Songhay","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-110.681,29.9446]}},
{"type":"Feature","properties":{"label":"Sumerian","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[45.6667,31.3]}},
{"type":"Feature","properties":{"label":"Tabo","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[143.305,-8.09387]}},
{"type":"Feature","properties":{"label":"Kambaata","family":"Afro-Asiatic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[37.9088,7.37582]}},
{"type":"Feature","properties":{"label":"Wageman","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[131.893,-13.8627]}},
{"type":"Feature","properties":{"label":"Wari'","family":"Wageman","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-64.56152,-10.69948]}},
{"type":"Feature","properties":{"label":"Siamou","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-4.92143,10.998]}},
{"type":"Feature","properties":{"label":"Southern Aymara","family":"Aymaran","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-70.3442,-17.1417]}},
{"type":"Feature","properties":{"label":"Bangime","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-3.77092,14.8116]}},
{"type":"Feature","properties":{"label":"Fur","family":"Furan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[23.6401,12.0455]}},
{"type":"Feature","properties":{"label":"Ma'di","family":"Central Sudanic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[31.8471,3.62499]}},
{"type":"Feature","properties":{"label":"Bardi","family":"Nyulnyulan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[122.906,-16.6274]}},
{"type":"Feature","properties":{"label":"Gaagudju","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[132.643,-12.5176]}},
{"type":"Feature","properties":{"label":"Yoruba","family":"Atlantic-Congo","insample":"1"},                              "geometry":{"type":"Point","coordinates":[3.67225,7.15345]}},
{"type":"Feature","properties":{"label":"Tuvinian","family":"Turkic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[94.36667,51.7]}},
{"type":"Feature","properties":{"label":"Iu Mien","family":"Hmong-Mien","insample":"1"},                              "geometry":{"type":"Point","coordinates":[101.17,20.83]}},
{"type":"Feature","properties":{"label":"Plateau Malagasy","family":"Austronesian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[47.1211,-19.5907]}},
{"type":"Feature","properties":{"label":"Yuchi","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-95.03933,35.96146]}},
{"type":"Feature","properties":{"label":"Trinitario","family":"Arawakan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-65.4096,-15.3331]}},
{"type":"Feature","properties":{"label":"Puinave","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-67.6886,3.92974]}},
{"type":"Feature","properties":{"label":"Bambara","family":"Mande","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-7.65,12.9]}},
{"type":"Feature","properties":{"label":"Ticuna","family":"Ticuna-Yuri","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-69.8723,-3.66289]}},
{"type":"Feature","properties":{"label":"Tommo So Dogon","family":"Dogon","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-3.28,14.756]}},
{"type":"Feature","properties":{"label":"Maricopa","family":"Keresan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-111.749,33.5123]}},
{"type":"Feature","properties":{"label":"Wubuy","family":"Gunwinyguan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[135.753,-14.2623]}},
{"type":"Feature","properties":{"label":"Yimas","family":"Lower Sepik-Ramu","insample":"1"},                              "geometry":{"type":"Point","coordinates":[143.572,-4.71731]}},
{"type":"Feature","properties":{"label":"Even","family":"Tungusic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[130.914,70.6687]}},
{"type":"Feature","properties":{"label":"Miyako","family":"Japonic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[125.363,24.7564]}},
{"type":"Feature","properties":{"label":"Chiquitano","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-59.9172,-17.6354]}},
{"type":"Feature","properties":{"label":"Aguaruna","family":"Chicham","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-77.9218,-5.30044]}},
{"type":"Feature","properties":{"label":"Hadza","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[35.0458,-3.83115]}},
{"type":"Feature","properties":{"label":"Sulka","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[151.891,-5.03471]}},
{"type":"Feature","properties":{"label":"South-Eastern Ju","family":"Kxa","insample":"1"},                              "geometry":{"type":"Point","coordinates":[20.7673,-19.688]}},
{"type":"Feature","properties":{"label":"Berta","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[34.7042,10.6474]}},
{"type":"Feature","properties":{"label":"Central Kalapuya","family":"Lower Sepik-Ramu","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-123.925,44.9861]}},
{"type":"Feature","properties":{"label":"Murriny Patha","family":"Southern Daly","insample":"1"},                              "geometry":{"type":"Point","coordinates":[129.70152,-14.74852]}},
{"type":"Feature","properties":{"label":"Yanomámi","family":"Jarrakan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-62.8522,2.48999]}},
{"type":"Feature","properties":{"label":"Bench","family":"Ta-Ne-Omotic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[35.7673,7.04682]}},
{"type":"Feature","properties":{"label":"Garrwa","family":"Garrwan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[137.72014,-17.4504]}},
{"type":"Feature","properties":{"label":"Sheko","family":"Dizoid","insample":"1"},                              "geometry":{"type":"Point","coordinates":[35.2826,7.05022]}},
{"type":"Feature","properties":{"label":"Koasati","family":"Muskogean","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-92.709,30.4096]}},
{"type":"Feature","properties":{"label":"Lao","family":"Tai-Kadai","insample":"1"},                              "geometry":{"type":"Point","coordinates":[102.46,19]}},
{"type":"Feature","properties":{"label":"Abkhazian","family":"Abkhaz-Adyge","insample":"1"},                              "geometry":{"type":"Point","coordinates":[41.159115,43.056218]}},
{"type":"Feature","properties":{"label":"Imonda","family":"Border","insample":"1"},                              "geometry":{"type":"Point","coordinates":[141.171,-3.31228]}},
{"type":"Feature","properties":{"label":"Washo","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-119.64,38.8184]}},
{"type":"Feature","properties":{"label":"Southern Yukaghir","family":"Yukaghir","insample":"1"},                              "geometry":{"type":"Point","coordinates":[154.375,64.218]}},
{"type":"Feature","properties":{"label":"Tol","family":"Teberan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-87.0372,14.6686]}},
{"type":"Feature","properties":{"label":"Ngarinyin","family":"Worrorran","insample":"1"},                              "geometry":{"type":"Point","coordinates":[126.433,-16.4006]}},
{"type":"Feature","properties":{"label":"Basque","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-1.31622,43.2787]}},
{"type":"Feature","properties":{"label":"Tidore","family":"North Halmahera","insample":"1"},                              "geometry":{"type":"Point","coordinates":[127.746,0.02461]}},
{"type":"Feature","properties":{"label":"Trumai","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-53.5717,-11.8119]}},
{"type":"Feature","properties":{"label":"Karok","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-123.315,41.8228]}},
{"type":"Feature","properties":{"label":"Shabo","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[35.223,7.64407]}},
{"type":"Feature","properties":{"label":"Kitja","family":"Jarrakan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[127.392,-17.5758]}},
{"type":"Feature","properties":{"label":"Miriwung","family":"Jarrakan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[128.889,-16.3596]}},
{"type":"Feature","properties":{"label":"Rotokas","family":"North Bougainville","insample":"1"},                              "geometry":{"type":"Point","coordinates":[155.154,-5.94339]}},
{"type":"Feature","properties":{"label":"Tehuelche","family":"Chibchan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-68.3235,-47.5796]}},
{"type":"Feature","properties":{"label":"Georgian","family":"Kartvelian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[43.78613,41.850397]}},
{"type":"Feature","properties":{"label":"Urningangg","family":"Giimbiyu","insample":"1"},                              "geometry":{"type":"Point","coordinates":[133.023,-13.4766]}},
{"type":"Feature","properties":{"label":"Kanoê","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-64.5812,-12.1789]}},
{"type":"Feature","properties":{"label":"Shasta","family":"Muniche","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-122.738,41.7587]}},
{"type":"Feature","properties":{"label":"Abun","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[132.416,-0.57073]}},
{"type":"Feature","properties":{"label":"Northern Yokuts","family":"Molof","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-119.721,36.3167]}},
{"type":"Feature","properties":{"label":"Tundra Nenets","family":"Uralic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[71.0234,66.1775]}},
{"type":"Feature","properties":{"label":"Muniche","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-76.426712,-5.7441796]}},
{"type":"Feature","properties":{"label":"Lavukaleve","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[159.119,-9.05569]}},
{"type":"Feature","properties":{"label":"Alamblak","family":"Sepik","insample":"1"},                              "geometry":{"type":"Point","coordinates":[143.316,-4.66307]}},
{"type":"Feature","properties":{"label":"Kayardild","family":"Tangkic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[139.489,-17.0695]}},
{"type":"Feature","properties":{"label":"Cholón","family":"Hibito-Cholon","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-75.9621,-9.23129]}},
{"type":"Feature","properties":{"label":"Nama (Namibia)","family":"Khoe-Kwadi","insample":"1"},                              "geometry":{"type":"Point","coordinates":[17.9767,-25.0747]}},
{"type":"Feature","properties":{"label":"West Itelmen","family":"Chukotko-Kamchatkan","insample":"1"},                              "geometry":{"type":"Point","coordinates":[156.30704,56.046173]}},
{"type":"Feature","properties":{"label":"Murle","family":"Surmic","insample":"1"},                              "geometry":{"type":"Point","coordinates":[33.988,6.69756]}},
{"type":"Feature","properties":{"label":"Taiap","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[144.506,-4.05047]}},
{"type":"Feature","properties":{"label":"Gaam","family":"Eastern Jebel","insample":"1"},                              "geometry":{"type":"Point","coordinates":[33.9797,11.4674]}},
{"type":"Feature","properties":{"label":"Kunama","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[37.5292,14.5879]}},
{"type":"Feature","properties":{"label":"Kenuzi-Dongola","family":"Nubian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[31.8992,21.2837]}},
{"type":"Feature","properties":{"label":"Zuni","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-108.782,35.0056]}},
{"type":"Feature","properties":{"label":"Yuracaré","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-65.1224,-16.7479]}},
{"type":"Feature","properties":{"label":"Awetí","family":"Tupian","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-53.391944,-12.381944]}},
{"type":"Feature","properties":{"label":"Takelma","family":"Isolate","insample":"1"},                              "geometry":{"type":"Point","coordinates":[-123.452,42.423]}},
{"type":"Feature","properties":{"label":"Bukiyip","family":"Nuclear Torricelli","insample":"1"},                              "geometry":{"type":"Point","coordinates":[143.111,-3.47169]}}]};